

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Figura 01

```{r m1}
matrix (c(1,2,3,4,5,6), nr = 2)
matrix (c(1,2,3,4,5,6), nr = 3)
matrix (c(1,2,3,4,5,6), nr = 6)
```

Figura 02

```{r m2}
matrix( c(1,2,3,4,5,6), nc = 2)
```

Figura 03

```{r m3}
meus_dados = c(1:10)
matrix(data = meus_dados, 5, ncol = 2, byrow = T)
```

Figura 04

```{r m4}
mat <- matrix(c(2,3,4,5,6,7), nr = 2)
mat
length(mat)


```
Figura 05

```{r m5}
dim(mat)
```
Figura 06

```{r m6}
nrow(mat)
```
Figura 07

```{r m7}
ncol(mat)
```

Figura 08

```{r m8}
mat
mat[1,2]
mat[2,2]
mat[1,3]
mat[,1]
mat[1,]

```
Figura 9

```{r m9}
matriz = 1:3
diag(matriz)
```

Figura 10

```{r m10}
vetor = diag(matriz)
diag(vetor)
```

Figura 11

```{r m11}
w <- matrix (c(2,4,8,12,16,20), nr = 3, ncol = 2)
w
t(w)
u <- t(w)
u
```


Figura 12

```{r m12}

w <- matrix (c(2,4,8,12), nr = 2, ncol = 2)
w
solve(w)
```

Figura 13

```{r m13}

mat1 <- matrix(c(2,3,4,5), nr = 2)
mat1
mat2 <- matrix(c(6,7,8,9), nr = 2)
mat2
mat1 * mat2
mat1 / mat2
mat1 + mat2
mat1 - mat2
```

Figura 14

```{r m14}

x = c(1:4)
x
y <- matrix(c(2,3,4,5), nr = 2)
y
x * y

```

Figura 15

```{r m15}


mat3 <- matrix(c(1:4), nr = 2)
mat3
dimnames(mat3) = (list(c('Linha1','Linha2'), c('Coluna1','Coluna2')))
mat3
```

Figura 16

```{r m16}

mat4 <- matrix(c(10,11,12,13), nr = 2)
mat4
mat5 <- matrix(c(14,15,16,17), nr = 2)
mat5
cbind(mat4, mat5)
rbind(mat4, mat5)
```

Figura 17

```{r m17}
mat4
c(mat4)
```